name: Minha primeira execução com Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.12.0-chrome-111
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run run-other-tests
          browser: Edge
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
